### ISSUE TITLE
why not use the request package

### ISSUE THREAD

**Issue by lujun9972** [xuchunyang/gitter.el#1]
If there is a curl exist,It will use curl to retrieve url. otherwise It will use url package instead

**Comment by xuchunyang** [comment]
主要是因为我没用过 request。另外，需要用到一个比较特殊的 API：发送一次请求，之后一直在监听，接受数据，因此需要直接操作 curl process，我猜测 request 可能封装的比较高级，操作底层反而不方便。Emacs 的 url.el 可能很难应用这个 API，差不多必须得要用 curl。

**Comment by xuchunyang** [comment]
> 需要用到一个比较特殊的 API

https://developer.gitter.im/docs/streaming-api

**Comment by lujun9972** [comment]
HTTP还能这么玩吗....
不带Content-Length头的情况下可以一直保持连接？
感觉完全颠覆了我对HTTP的理解
